[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    regression: Маркировка для регрессионных тестов.
    smoke: маркировка для смоук тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    courses: Тестовая маркировка.
